# render.yaml
services:
  - type: web
    name: fastapi-backend
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    workingDir: backend
    autoDeploy: true
